### PR TITLE
Add Light mode and algolia search to the docs

### PR DESCRIPTION
**Pull request by fakela**

### CODE REVIEW

**Comment by chefsale** [comment]
Screenshot 2023-06-16 at 10 51 34
Please fix this.

**Comment by chefsale** [comment]
Ask @matejpribanic for the light color pallete.

**Comment by fakela** [comment]
Algolia search implemented
Screenshot 2023-06-16 at 13 23 12
Screenshot 2023-06-16 at 13 23 08

**Comment by fakela** [comment]
> Screenshot 2023-06-16 at 10 51 34 Please fix this.

Screenshot 2023-06-16 at 13 23 52
fixed

**Comment by fakela** [comment]
> Ask @matejpribanic for the light color pallete.

done

**Review by chefsale — APPROVED** [review]

**Pull request merged**
